### ISSUE TITLE
Problem with dynamic compilation 

### ISSUE THREAD

**Issue by Tilaguy** [kiwicampus/Robotics-Test-Integration-Engineer#5]
I have a problem executing the command `bash startRobotics.sh # [args: -b {build}, -l {launch}]`. First, when I run it after having raised the container, it does not recognize it as a .sh file, so I have to first run the following command line:

     $ sed -i -e 's/\r$//' startRobotics.sh

After this if I can run it with the corresponding instruction but I always get this error, regardless of which module I have activated in the [*nodes_launch.yaml:*](../robotics/configs/nodes_launch.yaml):

     Starting Robot
     [INFO]: ROS2 Building new stuff...
     [INFO]:Packages to build: interfaces
     ' specified with --packages-up-to was not found

So for testing, I have to manually put the package name in line 99 of the build file [*startRobotics.sh*](../robotics/configs/tartRobotics.sh). Eg:

     `colcon build -- symlink-install --packages-up-to interfaces`.

The problem is that this only allows me to test one module at a time and I have not been able to carry out the execution at the time of what I am anticipating. Do you have any idea what could be happening?

**Comment by dadaroce** [comment]
Are you using a `.sh` terminal o `.bash`?

**Comment by Tilaguy** [comment]
Yes I'm,

**Comment by dadaroce** [comment]
What's your OS distribution? Are you using Ubuntu?

Btw, you could use:

```.bash
colcon build -- symlink-install --packages-up-to x_package y_package z_package 
```

**Comment by Tilaguy** [comment]
My laptop has Windows 10, but the container running VScode is on Ubuntu 20.04
![image](https://user-images.githubusercontent.com/39996527/172074678-41ab2a81-c53a-42f8-bd72-1d2263dfd457.png)

**Comment by dadaroce** [comment]
Just to clarify:

```
Ubuntu 20.04(Focal)[recommended] or Ubuntu 18.04(Bionic). In case you use another Linux based OS, the support by our side could be not enough to proper configure your dev-environment.
```

I don't have experience launching this stack in Windows.

**Comment by Tilaguy** [comment]
That's true, now I'm working on Linux and the problem fixed itself
